### ISSUE TITLE
Displaying non-validation related error messages

### ISSUE THREAD

**Issue by stephenkaraga** [Textalk/angular-schema-form#183]
Is there any way to "hook in" and apply/display non-validation related error messages to the form UI/fields?

For example.. I have a credit card payment form. The form gets submitted. Round trip to server happens. Actual payment processing fails for, say CVV and/or non-matching expiration date. I'd like to display those messages next to the corollary form fields - consistently with how Angular Schema Forms displays validation fail messages... 

so.. Is there any way to "hook in" and apply/display such non-validation related error messages to the form UI/fields?

**Comment by davidlgj** [comment]
Hi @stephenkaraga,

currently no. I guess you could do something with form type conditional and helpValue, but It wouldn't be as nice. 

Your use case is actually a bit complicated since it entails both server side validation *and* inter field validation. For solving the former I would usually recommend doing a custom form type that validates against the server, but that only works for one field. 

Your not the only one wanting some kind of support for server validation, see #177 and #178, so some kind of solution will probably come in the future :-)
