### ISSUE TITLE
Translation support?

### ISSUE THREAD

**Issue by stramel** [Textalk/angular-schema-form#213]
I am having a hard time of figuring out how one would be able to use something like [Angular Translate][at] to translate titles, placeholders, validationMessages etc. I've thought about overriding all the templates but that would be a pain to upkeep. I have tried using a function to translate the fields needed before it hits the HTML form, but the data isn't always there by that point. I have also tried waiting until the data is in place, but the form has already been rendered at that point. 

Any thoughts and/or suggestions would be greatly appreciated!

[at]: http://angular-translate.github.io/

**Comment by davidlgj** [comment]
We use gettext via Jed, http://slexaxton.github.io/Jed/, mostly because we
already have an existing gettext infrastructure.
But basically if you can translate a string via a function then that is the
same :-)

So we solve it by setting description, title etc in the form definition to
the actually translated value or in some cases let the backend generate a
schema with titles and descriptions in the appropriate language. And of
course a global `validationMessages` with all the standard errors , and
sometimes override them in the form definition.

The translation all happens *before* we put schema and form on the scope.
So it all happens before schema form is even in the picture. Another way of
doing it would be to use a recursive `postProcess` function and translate
every title, description, placeholder and validation you can find in the
final form structure before the form is rendered.

Does that help?

Wed Jan 14 2015 at 17:37:59 skrev Michael Stramel <notifications@github.com

**Comment by stramel** [comment]
@davidlgj @Dervisevic I have been trying to do the `postProcess` function that translates every title but since the data is coming from the server asynchronously. The data isn't necessarily there at the time. 

I was wondering if it would make sense to add a `| translate`/ `translate directive` to all existing templates. Then during initialization check if the translate filter/directive is defined, if not define them as pass through functions? This would allow users to take advantage of their defined translate functionality and the other users wouldn't have to worry about it. 

Also, I had seen gettext, but not Jed, thanks for sharing!

**Comment by davidlgj** [comment]
Adding an empty directive and filter is a possible solution. But it will
need a service as well for those times when you need to translate a sting
in a add-on.

I guess we could do that but what I really don't get is why you just don't
wait for the translations to be loaded before you add schema and form to
scope?

That way you can translate schema and form definition beforehand or safely
do it in a `postProcess`

Thu Jan 15 2015 at 15:13:16 skrev Michael Stramel <notifications@github.com
>:

@davidlgj <https://github.com/davidlgj> @Dervisevic

**Comment by stramel** [comment]
@davidlgj That works for me! It isn't the prettiest but it will do, thanks!

**Comment by lucasgranberg** [comment]
This is what I did and it seems to work.

```javascript
        angular.forEach($scope.schemaDef.properties,function(property,key){
            $translate(property.title).then(function(translation){
                $scope.schemaDef.properties[key].title=translation;
            })
        });
```

**Comment by EnobaDevelopers** [comment]
How can i do it if my schema comes directly from a json file?

**Comment by HeidemannMarkus** [comment]
+1

**Comment by shravanmahankali** [comment]
Has anyone got this working better?

**Comment by shravanmahankali** [comment]
angular-translate (https://angular-translate.github.io/docs) seems to work very well for me as well! thanks for the pointers.

**Comment by lucasgranberg** [comment]
Now after almost 2 years I had to implement translation for schema form again. Just for reference this is what I did. I am using ngtemplates to make my templatecache so I added these to the templatecache.
```js

        ngtemplates: {
            dist:{
                options: {
                    module: 'appidappiApp',
                    htmlmin: '<%= htmlmin.dist.options %>',
                    usemin: 'scripts/scripts.js'
                },
                cwd: '<%= yeoman.app %>',
                src: [
                    'views/**/*.html',
                    'decorators/bootstrap/*.html'
                ],
                dest: '.tmp/scripts/templates.js'
            }
        },
```
This means I also have to use the templatecache when devving.

I simply copied all the bootstrap templates to app/decorators/bootstrap. Then I manually inserted the |translate filter from https://github.com/angular-translate/angular-translate in all the templates where there is text to be displayed.

I am using wiredep so I added excluded the included bootstrap decorators.

```js

        wiredep: {
            app: {
                src: ['<%= yeoman.app %>/index.html'],
                ignorePath:  /\.\.\//,
                exclude:[
                    'bower_components/angular-schema-form/dist/bootstrap-decorator.js'
                ]
            }
```

It is a bit more work to do it this way but it is better than the $translate.instant method that assumes all the translations are loaded.

It would be sweet if angular schema form would have som kind of overrideable filter on all places where there is text in templates but I am not opening an issue for that right now. It would add a little overhead for people not using translations but it would make integration easier.

This idea could even be taken further by having a option to use translationDomain+options.path.join('.') as the default value if no title is set as my translation structure tends to follow the schema.

**Comment by anasofiapaixao** [comment]
I also stumbled upon this issue, and the `$translate.instant` approach was not enough because those fields would not be picked up by `$translate.use()`, which meant that on-the-fly language switching does not work. I found a better (although still hackish) approach for anyone using webpack, similar to Lucas' but without taking ownership of the template code by using `string-replace-loader`. I added the loader to my `devDependencies` and then configured it in my `webpack.config.js` loaders like this:

```
module.exports = {
  (...)
  module: {
    rules: [
      (...)
      {
      // workaround for translating schema form fields in a way that is handled
      // by $translate.use()
      test: /bootstrap-decorator\.js$/,
      loader: 'string-replace-loader',
      options: {
        search: '(?<!\\.)(?<!: )(form|tab)\\.title(?![a-zA-Z])',
        replace: '$1\.title \| translate',
        flags: 'ig',
        strict: true
      }
    }
    ]
  },
  (...)
};
```

This loader preprocesses files by doing the configured find & replace operations before the file is included in the bundle. I'm looking for the instances of `form.title` and `tab.title` (for the titles in form tabs) that appear in the template cache strings, and appending the `| translate` filter. I am using negative lookaheads to avoid matching e.g. `titleMap` and negative lookbehinds to avoid the specific `form.title` occurrences that are outside the template cache, which means that while this regex works for `angular-schema-form-bootstrap` 0.2.0, it might break and have to be revised with any version upgrade, even patch.

It's a bit brittle but at least does not require taking full ownership of the bootstrap template code.
