### ISSUE TITLE
Toggle readonly flag for form fields and change form fields enabling (disabled="disabled", ng-disabled="form.readonly")

### ISSUE THREAD

**Issue by flashnot** [Textalk/angular-schema-form#225]
Hello. Please, help.

I have in app.js:
$scope.schema = {
&nbsp;&nbsp;&nbsp;&nbsp;...
&nbsp;&nbsp;&nbsp;&nbsp;"readonly":true
};
$scope.form = [
&nbsp;&nbsp;&nbsp;&nbsp;"nick",
&nbsp;&nbsp;&nbsp;&nbsp;"email",
&nbsp;&nbsp;&nbsp;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"key": "message",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"type": "textarea",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"placeholder": "Problem description",
&nbsp;&nbsp;&nbsp;&nbsp;},
&nbsp;&nbsp;&nbsp;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"type": "submit",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"style": "btn-info",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"title": "OK"
&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;];
$scope.model = {};
and in index.html:
&lt;form sf-schema="schema" sf-form="form" sf-model="model"
&nbsp;&nbsp;&nbsp;&nbsp;&lt;div class="row">
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;div class="col-md-6">
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;div sf-insert-field="['nick']">&lt;/div>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/div>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;div class="col-md-6">
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;div sf-insert-field="['email']">&lt;/div>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/div>
&nbsp;&nbsp;&nbsp;&nbsp;&lt;/div>
&lt;/form>

-------------

I need button which can toggle form fields state (enable/disable for editing). How to implement it? Thanks, for any help.

**Comment by davidlgj** [comment]
Hi @flashnot 

There are two ways:
1) Hook in an `onChange` on the button (or checkbox?) and re-render the form by changing the schema, removing or adding the "readonly" attribute.  Currently it's a simple $watch so either the form object or the schema needs to be a different object instance for it to trigger a re-render. 
You can use angular.copy to prepare two versions of the schema, one which is readonly and one which is not.

2) ...or you can use the type [conditional](https://github.com/Textalk/angular-schema-form/blob/master/docs/index.md#conditional). Make two `conditional` with expressions that listen to the same value but one that triggers when its true and one that triggers when its false. So one of them is always visible. You can then set one of them to be disabled and one to not be disabled with the form option `readonly`.

I'm closing this issue since it's neither a bug nor and enhancement request. Try stackoverflow if you have more problems, tag it with angular-schema-form and we will see it :-)

**Comment by EtiAggarwal** [comment]
The second method of using two conditionals worked for me, but when I switched to alpha3 it stopped working. I am using the conditionals inside an array.

**Comment by Anthropic** [comment]
@EtiAggarwal can you make an issue with a plunker?
