### ISSUE TITLE
validation doesn't work for radios

### ISSUE THREAD

**Issue by melnikaite** [Textalk/angular-schema-form#230]
http://jsfiddle.net/mdmg0ad3/

**Comment by davidlgj** [comment]
Yep, that's a bug.

**Comment by kupuguy** [comment]
I think that a simple fix for this would be to include the attribute `ng-required="!$$value$$"` in the input field attributes.

**Comment by davidlgj** [comment]
@kupuguy sadly it's not that simple :-( First of it should only be required if the schema says so, not otherwise. And secondly we'd like to use our own error messages, not the browsers. 

Slapping on the directive `schema-validate="form"` on the input does indeed validate and stop submit, but I'll have to write some custom code to get error messages in the right place.

**Comment by melnikaite** [comment]
It seems cause of it is `ng-repeat` in the template
I faced the same issue in my custom plugin

**Comment by orderofout** [comment]
It seems like this issue is resolved but not merged with the master branch? Any timeframe to this or how I can get the fix?

**Comment by ulion** [comment]
I can not image it do not support radios type's required!!!

how could we fix this?

**Comment by davidlgj** [comment]
Fixed in 0.8.0, finally.
