### ISSUE TITLE
[Documentation] Checking $valid on controller scope

### ISSUE THREAD

**Issue by quietlyconfident** [Textalk/angular-schema-form#259]
This is a request for help / question regarding the documentation's mention of [accessing the FormController](https://github.com/Textalk/angular-schema-form/blob/master/docs/index.md#handling-submit).  Hopefully I'm doing it wrong, in which case, just consider this a data point on where the documentation could possibly use improvement. (at least for me :)

In my use case, I don't want to have a submit button in the form, I want to just watch the validity of the form from my page controller and do stuff as the form becomes valid / invalid.

I get how, as in the example, you can have a submit button and pass the form instance as an argument to the onSubmit function.  But how to monitor the validity of the form outside of the submit button is unclear.

First issue is that the documentation seems to imply that if you put a "name" attribute on a form, you can **access** that form.  Assuming I understand correctly what is happening, this is only true in the special case where you are trying to access the form from within the form element itself, the outer scope does not necessarily receive the form instance.  So I think the documentation should be clarified to read something like "If you put a name attribute on your form, you can access the FormController **inside the scope of the form element itself.  To access the FormController outside the scope of the form element, for example on an external page controller, you'll need to do something else.**"

Second issue is exactly how that would work, e.g. what is "something else".  As suggested in the comments to another issue, in the controller for the page, I created an object (`$scope.object_form = {}`), and then gave the form a name that would place it in that object (`<form name="object_form.myForm">`).

Now, in my outer page controller, I can deep - $watch that object, and see its' $valid property, but the form object doesn't seem to update itself (e.g. triggering more executions of the $watch function) as the user manipulates the form, e.g. causing fields to be valid or invalid.

So I am somewhat at a loss as to how to monitor the validity of a form in the scope of the page controller.

**Comment by Dervisevic** [comment]
Ok I'm not 100% sure the exact way it should be done, as all the times i've used it I've sent it an argument on a click and used it that way, but this [Stackoverflow post](http://stackoverflow.com/questions/21574472/angularjs-cant-access-form-object-in-controller-scope) suggests another way to get a hold of the formController. This is more of an angular thing rather than ASF/tv4, i'm sure there are good solutions out there.

When you've got a hold of it you can just broadcast the validate event, and then you use the formController that you got a hold of to check it validity and so forth.

```javascript
scope.$broadcast('schemaFormValidate');
if (form.$valid) {
   ...
}
```

I hope this answers your questions, or at least nudges you in some direction.

**Comment by pitchiah** [comment]
Hi Dervisevic, your solution works perfectly
