### ISSUE TITLE
Combining $scope.schema & $scope.form in the same Json file

### ISSUE THREAD

**Issue by ssolida** [Textalk/angular-schema-form#291]
I'm trying to combine my form  & my schema in the same Json file, to allow my server to pass the full configuration of the form.
Everything looks to work perfectly, except on using the __onChange__ function, which has to be passed as string for a valid json :

```json
{
  "config_schema" :
  {
    "type": "object",
    "title": "Comment",
    "properties": {
      "db": {
        "title": "Database",
        "type": "string",
        "enum": ["Postgress","Mango DB","mySQL","Oracle","Cassandra"]
      }
    }
  },
  "config_form" :
  [{
        "type": "section",
        "items": [
          {
          "key": "db",
          "title": "database",
          "onChange": "function(modelValue,form) {console.log(modelValue);}"
          }
        ]
  }]
}
```

When I select a value on my field I have syntax error :

```
Error: [$parse:syntax] Syntax Error: Token '{' is an unexpected token at column 27 of the expression [function(modelValue,form) {console.log(modelValue);}] starting at [{console.log(modelValue);}].
```

**Comment by davidlgj** [comment]
Hi @ssolida,

`onChange` takes a function or a string with an *angular expression* (see [docs](https://github.com/Textalk/angular-schema-form/blob/development/docs/index.md#onchange)) and `"function(modelValue,form) {console.log(modelValue);}"` is not an angular expression.

So if you need to rewrite it to use angular expressions or process the form definition before you give it to angular schema form  (using new Function() or eval).

**Comment by plong0** [comment]
Something to consider is if you want your server to be serving language-specific content.  I guess "code-on-demand" can be cool, but it can easily tie your server and client very tightly together.

I have a similar project where I am having my server modules deliver schema and form definitions, and for callbacks I pass the function name and leave it up to the client to implement that function however they need to.  I like this approach, because I can easily envision using the same server with clients implemented as angularjs or C++ or anything else ;)
