### ISSUE TITLE
Required error message

### ISSUE THREAD

**Issue by ravivit9** [Textalk/angular-schema-form#299]
When a required field is left as null the error message shows the schema key value instead of the field title.  I am keeping key name as database field name so that it will be convenient in server-side  scripting for field mapping.

e.g..

```
{
  "schema": {
    "type": "object",
    "title": "",
    "properties": {
      "org_name": {
        "title": "Organisation Name",
        "type": "string",
        "maxLength": 100
      }
    },
    "required": [
      "org_name",
    ]
  },
  "form":[
    {
      "key": "org_name",
      "type": "text",
      "placeholder": ""
    }
 ]
}
````

From the above example the error shows as below:
---- Missing required property: org_name

But I would like to display it as 
---- Missing required property: Organisation Name or what ever specified in schema title property of the field.

Can I mention custom error message like "Organisation Name is a required field".

**Comment by davidlgj** [comment]
I've recently done some changes to the validation messages, see the docs in the development branch: https://github.com/Textalk/angular-schema-form/blob/development/docs/index.md#validation-messages

So a new thing that is coming out is message interpolation, so then you can have a custom message that uses `{{ title }}` to get the title of the field rather than the key. (I also changed the defaults to do just that)

Aiming for it to be out on friday, but it needs more testing, so If you have time to try the version in the development branch please do!

**Comment by davidlgj** [comment]
It's now out in 0.8.0. I'm closing the issue but feel free to open it again if you have a problem.
