### ISSUE TITLE
'Required' validation messages should not be first on the error message order of precedence

### ISSUE THREAD

**Issue by peluja1012** [Textalk/angular-schema-form#322]
Looking at the code, it seems that only one error message is displayed at a time. However, it would be nice that other error messages took precedence over the 'Required' error message. For example, if I have a property of type 'integer' that is required and the user types letters, ideally the user would see a ```Not a number``` error message and not a ```Required``` error message.

This is currently what I'm seeing:

![image](https://cloud.githubusercontent.com/assets/616158/6838841/2f09c4ae-d336-11e4-9723-c093ba54c8e3.png)

I have put together a [plnkr](http://plnkr.co/edit/pNJRqZAqrazV0chBEgR7?p=preview) that shows this.

**Comment by oatkiller** [comment]
:+1: This is a big pain point for me as well

**Comment by davidlgj** [comment]
How about this, if the *viewValue* of the form is not empty then the required validation message should not be shown (or last in the list), otherwise it should be first? 

I think this pops up since the input is an integer which means that the model value is empty and that's why you get the required instead of the "Not an integer". Marking it as a bug.
