### ISSUE TITLE
Event-Handlers

### ISSUE THREAD

**Issue by jannickfahlbusch** [Textalk/angular-schema-form#345]
I read the docs but didn't found anything regarding handlers on the fields like onBlur(), onFocus() or something.

Do i haven't seen it, or is this functionality not implemented yet?

**Comment by davidlgj** [comment]
Hi @jannickfahlbusch! The docs covers nearly everything, at least everything that is supported. There is `onChange` for some fields but no other events as of now. What is your use case?

**Comment by jannickfahlbusch** [comment]
I would use it, to register functions to these events. 

I want to execute some actions inside of a function, when i'm leaving/entering a field and so on

**Comment by davidlgj** [comment]
Sure, but what is the use case? What is the problem you are trying to solve?

**Comment by jannickfahlbusch** [comment]
I need to execute a function check() when the user has blurred the field. 

check() will dynamically add or remove fields, depending on the input of the user.

**Comment by davidlgj** [comment]
I'm not sure if or when we'll implement support for more events, I guess I'd like to do it some other then adding a lot of `ng-*` to the templates. 

In the meantime I suggest you listen to onBlur events from the form the old fashioned way with an ordinary event listeners :) Don't forget to broadcast a `schemaFormRedraw` event and issue a `$apply()` after you've changed the form.

**Comment by subhendupsingh** [comment]
Exactly what event should i listen to?? I have tried "onBlur","ng-blur","ngBlur","blur" but no success.

Moreover is there a way to broadcast schemaFormValidate and get back the result without any changes on the UI, like validation errors,success etc.

Use Case: I want to set form autosave on blur (or after 2 seconds of inactivity whichever is possible), only when the madatory fields are filled, otherwise nothing happens.

**Comment by jannickfahlbusch** [comment]
Currently, there is only the support of onChange.

I'm working on a PR, wich will add onBlur and other event-handlders.

**Comment by subhendupsingh** [comment]
Allright!

Any thoughts on this:

Moreover is there a way to broadcast schemaFormValidate and get back the result without any changes on the UI, like validation errors,success etc.

**Comment by davidlgj** [comment]
@subhendupsingh by "old fashioned way" I was referring to ordinary DOM Events, i.e using jQuery or by addEventListener. 

`schemaFormValidate` forces a validation on all fields just so that the UI changes,  but the default behavior is to validate a field on change so you can always just check the state of the form controller.

**Comment by murrutia8k** [comment]
Hi, I'am using onchange with a input date, but I need the function was executed when I loose focus (onBlur) in the field, not always when change... supose I need to change date from 2017-08-12 to 2017-08-11... But the function is executed for 2017-08-1 (when I delete the last "2" character) and then when I complete date to 2017-08-11.

Any news about other events? I need to resolve this issue as commented before : "by "old fashioned way" I was referring to ordinary DOM Events, i.e using jQuery or by addEventListener."?

Thanks for your comments.

**Comment by seseso** [comment]
Hi, any news about this? I have the same requirement!

Thanks

**Comment by murrutia8k** [comment]
Hi,

We use this workaround as commented in this other issue:
https://github.com/Textalk/angular-schema-form-datepicker/issues/24
Let me know if this helps you.

2017-10-20 10:43 GMT-03:00 seseso <notifications@github.com>:
