### ISSUE TITLE
sf-render-finished event

### ISSUE THREAD

**Issue by bibidon** [Textalk/angular-schema-form#381]
Hi. 

How I can listen event like that "sf-render-finished" but when all children append to the document ?

**Comment by davidlgj** [comment]
Sadly there is no such event, `"sf-render-finished"` is called wen the top level of form fields are rendered, so then its up to those directives to pull in any children and so forth. Depending on your use case though it might work with just a `$timeout` to wait for next tick, since all templates are pre-cached everything should happen synchronously.
