### ISSUE TITLE
Invalid type: number (expected string)

### ISSUE THREAD

**Issue by stephenbaidu** [Textalk/angular-schema-form#404]
When a form field of type `string` is assigned a number programmatically, form validation fails with `invalid type: number (expected string)`. Am of the view that all numbers (in this case) can be cast to strings, so this field should not fail validation. Any ideas?

**Comment by davidlgj** [comment]
This is expected behavior of validation with a JSON Schema validator (its in the specification), and how tv4, the validator we use, work. So it's not something we can change. 

Two thoughts spring to mind: First is check the type of the field your setting in the schema and use parseInt or parseFloat when it's appropriate before updating the model. Or instead of updating the model directly fill in the inputs instead and let angular and its parsers do their work to update the model with the correct value.

**Comment by stephenbaidu** [comment]
Understood. Thanks.

**Comment by davidlgj** [comment]
No prob :)
