### ISSUE TITLE
Concatonating fields

### ISSUE THREAD

**Issue by mogmog** [Textalk/angular-schema-form#405]
Loving schema form, one question, If I have two fields, eg: firstName and secondName, is it possible to make these two fields automatically populate a third field that would contain eg firstName + ' ' + secondName?

**Comment by davidlgj** [comment]
Depends on what you mean by a third field. Is it only for presentation? I.e. should be there but disabled or should it bind against its own field which gets the concatenated version? Maybe even editable? 

The first version is simple to do with a `template` type and a small template, here is an example: http://schemaform.io/examples/bootstrap-example.html#/9f5028d4057ca4f0b475

I kept the template as simple as possible so its needs some love to make it look good, and note that you can supply an url to a template via `templateUrl` option instead of an inline template. 

The second version could be done via an function that copies last and first to the third fields model via `onChange` triggers.

**Comment by mogmog** [comment]
It should bind against its own field in the model. The onChange approach sounds like a win.
