### ISSUE TITLE
select value not initialised from model

### ISSUE THREAD

**Issue by TrevorPage** [Textalk/angular-schema-form#462]
The problem I have seems to be demonstrated in this schemaform.io example. (I didn't put this example together; I think I found it on a Stackoverflow question).

http://schemaform.io/examples/bootstrap-example.html#/c0cf38b387b84e567176

What this demonstrates is that although the model has a value for the select, the select is not initialised to show that value. Instead it is blank. 

For most of my selects I have been using Angular-schema-form-dynamic-select, and with that library I have never had this problem. But for a particular page I wish to use a standard ASF select (because I want to use a custom decorator derived from it).

**Comment by nicklasb** [comment]
Just wanted to mention that ASFDS only registers itself as a default `if ((schema.type === 'string') && ("enum" in schema))` [here (the dev branch use the same condition)](https://github.com/OptimalBPM/angular-schema-form-dynamic-select/blob/master/src/angular-schema-form-dynamic-select.js#L6), so I have no idea how ASFDS could interfere with the standard select of ASF when `type:"select"` is specified. 

Is there some other way schemaFormProvider.defaults is used that I don't understand? Or are add-ons further interacted with in some way that is not known to me? 

Looking at the ASF source, I cannot find anything obvious. Granted, I am not very well versed in the ASF code base.

**Comment by nicklasb** [comment]
Ok, the problem seems to be that the built-in ASF select only calls enumToTitleMap() [when it is invoked via default schema types](https://github.com/Textalk/angular-schema-form/blob/development/src/services/schema-form.js#L147). 

I don't know where to put it, but it should probably have that call in some kind of ng-init-functionality in its template instead, if there is no other better place for it.

**Comment by chesterlau** [comment]
I am currently experiencing this problem and had to work out a simple workaround without editing the library.

We can select the value in the select list that we want after the form is rendered through the val() function. A timeout is set in order to wait for the form to be rendered onto the page so that the DOM can be selected.

setTimeout(function () {
   $("select[name='mySelectList']").val(model.myValue);
 }, 100);

**Comment by nicklasb** [comment]
Ok, good, so now there is some kind of a work around, at least.

**Comment by davidlgj** [comment]
I thought this might be related to https://github.com/Textalk/angular-schema-form/pull/418 but it doesn't seem like it. It's probably related to array handling.

**Comment by davidlgj** [comment]
My bad, it indeed looks like it was `trackBy`. After updating the demo to 0.8.4 (which reverted the PR that introduced the bug), http://schemaform.io/examples/bootstrap-example.html#/c0cf38b387b84e567176 seems to work fine.

**Comment by davidlgj** [comment]
Feel free to re-open if you disagree :)

**Comment by nicklasb** [comment]
Hm. It seems I was wrong about this one, I think I misread the example. :-/
