### ISSUE TITLE
name attribute created different on decorators

### ISSUE THREAD

**Issue by ngabello** [Textalk/angular-schema-form#515]
For some of the decorators the name attribute is generated like name="{{form.key.slice(-1)[0]}}" but for the radio-buttons, radios and radios-inline they are generated like name="{{form.key.join('.')}}". Is this by design? This becomes an issue when I loop through the control names when the form is submitted to perform my model validation.

**Comment by davidlgj** [comment]
It's sort of by design :) But not a good design. The names started out being `form.key.join('.')` to be unique, that then got changed to `form.key.slice(-1)[0]` so that form autofill could work sometimes. I.e. something like 'customer.firstname' won't get autofilled, but 'firstname' will. 

There are two PR's regarding id's and names, #496, #463, so a better handling is in the works. Basically we need better optional values, probably will have the unique values as default though. 

As  side note? Just curious :)  Why are you looping over the controls to perform validation? Why not a `schemaFormValidate` event + checking form controller if the entire form is valid or not?

**Comment by ngabello** [comment]
the schema form does not allow for business rule validation, so I call the model to validate the input and then call $scope.$broadcast(form Item, msg, false);

````Javascript
validateAgeFirstLicensed: function (validationStates) {
        $log.debug('Validation age first licensed');
        if (this.DateOfBirth && this.AgeFirstLicensed) {
          if (isNaN(this.AgeFirstLicensed)) {
            validationStates.push({property:'AgeFirstLicensed', message:'notANumber', state:false});
          }else{
            validationStates.push({property:'AgeFirstLicensed', message:'notANumber', state:true});
          }
          var birthDate = new Date(this.DateOfBirth.replace(/-/g, "/"));
          var currentDate = new Date();
          var age = moment(currentDate).diff(birthDate, 'years');
          validationStates.push({property:'AgeFirstLicensed', message:'ageLowerRange', state:parseInt(this.AgeFirstLicensed, 10) >= 14});
          validationStates.push({property:'AgeFirstLicensed', message:'ageUpperRange', state:parseInt(this.AgeFirstLicensed, 10) <= age});
        }
      },
```
````html
 {
                      key: "driver.AgeFirstLicensed",
                      placeholder: "",
                      title: "Age first licensed",
                      "labelHtmlClass": "float-left",
                      "fieldHtmlClass": "float-right form-50",
                      "htmlClass": "test",
                      validationMessage: {
                        "notANumber": "Please enter a valid first licensed age.",
                        "ageLowerRange": "Sorry, first licensed age cannot be lower than 14 years.",
                        "ageUpperRange": "Sorry, first licensed age cannot exceed driver's current age."
                      }
                    },
```
