### ISSUE TITLE
Is there a way to use an ng-required in the schema?

### ISSUE THREAD

**Issue by ngabello** [Textalk/angular-schema-form#535]
I have several controls where validation depends on previous responses to questions. I use the required attribute in the schema but was wondering if there was an ng-required.

**Comment by ngabello** [comment]
Basically I have some controls that are required only if others are answered a specific way. I am currently using ng-required. Can this framework schema definition support an required condition??

**Comment by davidlgj** [comment]
@ngabello Currently not really since we don't support `oneOf` or `anyOf` schema definition yet. (we're working on it).

What you can do is to force it in the form definition instead with a combination of `condition` and `required`. I.e. you can say that a field is required in the form defintion, and by listing a field twice, but with different conditions you can selectively give the user a required field. 

There is an example on the demo page, http://textalk.github.io/angular-schema-form/examples/bootstrap-example.html

Choose: "hack: conditional required"

**Comment by ngabello** [comment]
I solved it using a custom form type, not ideal but effective.
````html
div class="form-group {{form.htmlClass}} schema-form-select"
     ng-class="{'has-error': form.disableErrorState !== true && hasError(), 'has-success': form.disableSuccessState !== true && hasSuccess(), 'has-feedback': form.feedback !== false}">
  <label class="control-label {{form.labelHtmlClass}}" ng-show="showTitle()">
    {{form.title}}
  </label>
  <select ng-model="$$value$$"
          ng-model-options="form.ngModelOptions"
          ng-disabled="form.readonly"
          sf-changed="form"
          class="form-control {{form.fieldHtmlClass}}"
          schema-validate="form"
          ng-options="item.value as item.name group by item.group for item in form.titleMap"
          name="{{form.key.slice(-1)[0]}}"
          ng-required="{{form.requiredCondition}}">
  </select>
  <div class="help-block" sf-message="form.description"></div>
</div>
```
