### ISSUE TITLE
checkboxes: TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by punknroll** [Textalk/angular-schema-form#554]
Hi, when i select a checkbox I get the following error using the development branch which I need because of the new builder.

I made a plnkr for that:

http://plnkr.co/edit/qvsyjw?p=preview

Thanks for info.
Andi

**Comment by punknroll** [comment]
I found out that checkboxes don't have a ngModel. The form remains invalid as the model of the checkboxes is missing.

**Comment by davidlgj** [comment]
Hi @punknroll. Thank you for the nice plunkr. Made it easy to find :+1: 

It was the model array that didn't get initialized properly. I made a hotfix with a fix and it's both out in master (0.8.10) and development branch.

Btw, you don't need the development branch to use the new builder. It's all released in master as well, just make sure to include the decorator from angular-schema-form-decorator repo instead of the one in dist/.

**Comment by punknroll** [comment]
Hi @davidlgj . Wuhooo!!!! Thanx for the fix!!!!

I already discovered that the new builder is in the master branch as well!
