### ISSUE TITLE
Another schema form instance inside an add-on

### ISSUE THREAD

**Issue by nicklasb** [Textalk/angular-schema-form#626]
Hi,

I am creating an add-on for ASF that loads a separate ASF instance. Nested ASF, like.
The reason is that I want separate validation for that and the ability to build completely separate and specialized UI:s for some complex structures.

However, I am not getting the ASF inside the add-on to work properly. It won't render. 
Now I haven't tried very hard yet, just asking if there is anything that can be said off the bat that makes that impossible?

**Comment by nicklasb** [comment]
Ok, so this got weird, if I add another, empty form tag before the schema form tag, it renders.
I'll be back.

**Comment by nicklasb** [comment]
Ok, that or using an ng-form instead of a form. No idea why as the main schema form is a regular form.

**Comment by nicklasb** [comment]
I will not immerse myself with the form thing, and will just accept that ng-form makes it work.
For reference, this is the add-on I am working on:
https://github.com/OptimalBPM/angular-schema-form-complex-ui

**Comment by nicklasb** [comment]
The reason it worked with ng-form and not form was that forms cannot be nested in HTML. 
ng-form was designed to work around that, however there are other issues, for example ng-submit cannot be used inside it, so it is not actually a real form. ASFCUI  instead has to use its own submission handling.

**Comment by a-polito** [comment]
Hi @nicklasb,
I'm having the same problem. Basically I'm working on a very complex UI that loads many custom components  (I'm using angular 1.5 components) and one of them uses a nested schema form, so for this reason I had to convert the form tag inside the component to another tag such as div or ng-form. Despite this, in the validation phase, triggering the schemaFormValidate event, I'm unable to access any form controller because a "form" does not exists! Also using the angular ng-form tag doesn't provide any FormController.

Did you find a way to access the $valid property or an alternative way to to check the form validity?

**Comment by nicklasb** [comment]
I only had two levels, so in the bottom levels I think I used actual forms, but I can't check now. 
Either way, adding ng-form would be a nice way to tell ASF that there is something there.
